name: "publish package to npm" # 指定工作流程的名称为 "publish package to npm"

on: push  # 当代码推送到仓库时触发此工作流程

jobs:  # 定义一个或多个作业
  publish:  # 定义名为 "publish" 的作业
    runs-on: ubuntu-latest  # 指定作业在最新版本的 Ubuntu 上运行
    steps:  # 定义作业的执行步骤
      - name: checkout  # 步骤的名称为 "checkout"
        uses: actions/checkout@v4  # 使用 GitHub 官方的 actions/checkout 动作，版本为 v4
      - name: node  # 步骤的名称为 "node"
        uses: actions/setup-node@v4  # 使用 GitHub 官方的 actions/setup-node 动作，版本为 v4
        with:  # 提供配置参数
          node-version: '20'  # 指定 Node.js 的版本为 20
          registry-url: https://registry.npmjs.org  # 设置 NPM 的注册表 URL 为 https://registry.npmjs.org
      - name: publish  # 步骤的名称为 "publish"
        run: npm publish --access public  # 运行命令以将包发布到 NPM，--access public 用于确保包是公共可访问的
        env:  # 设置环境变量
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}  # 设置 NODE_AUTH_TOKEN 环境变量为 NPM 认证令牌，从 GitHub 仓库的 secrets 中获取